destination: ./docs
collections:
  articles:
    output: true
    permalink: /blog/:title
    layout: article
  experiences:
    output: false
  projects:
    output: false
exclude:
  - README.md
  - Procfile.dev
  - bin/
  - tailwind.config.js
  - css/input.css
url: https://marc-chamberlin.com
